In [38]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import pickle
%matplotlib inline

In [6]:
dataset=pd.read_csv(r'C:\Users\Lenovo\Desktop\Mechademy\Expander_data.csv')

In [32]:
dataset

,Timestamp,Suction Pressure (psig),Suction Temperature (F),Total Flow (gpm),Speed (rpm),By-pass Valve Position (%),Discharge Pressure (psig),Discharge Temperature (F),Run Status
0,1/4/2020 21:20,596.100853,-229.436683,7925.800487,2999.411045,6.0,226.044931,-227.614448,NaN
1,1/4/2020 21:20,596.838217,-230.453708,8085.917724,2989.706617,6.0,217.150974,-228.668636,NaN
2,1/4/2020 21:20,596.468895,-229.545356,7902.175243,3006.331679,6.0,226.054086,-227.755324,NaN
3,1/4/2020 21:20,603.568271,-230.309438,7991.808959,3010.487486,6.0,226.016182,-228.489113,NaN
4,1/4/2020 21:21,595.407372,-229.767969,7871.560747,2986.665518,6.0,227.769383,-227.971795,NaN
5,1/4/2020 21:21,594.415722,-229.595078,8142.742624,3012.234024,6.0,207.115318,-227.815428,NaN
6,1/4/2020 21:21,597.170202,-230.133506,7964.420754,3012.518826,6.0,220.471189,-228.346539,NaN
7,1/4/2020 21:21,603.331813,-229.551912,8139.809812,3010.796870,6.0,218.614349,-227.744417,NaN
8,1/4/2020 21:22,595.013360,-229.575425,8047.233812,2995.877540,6.0,218.631897,-227.790784,NaN
9,1/4/2020 21:22,598.340373,-229.808081,8125.062853,3011.871916,6.0,212.304464,-228.027485,NaN
10,1/4/2020 21:22,604.875850,-230.077084,8033.732791,2994.495534,6.0,227.548634,-228.294492,NaN
11,1/4/2020 21:22,597.126396,-229.536504,7967.256334,2986.110447,6.0,222.473615,-227.752273,NaN
12,1/4/2020 21:23,594.506367,-229.957518,8077.740153,2997.249747,6.0,212.174912,-228.173239,NaN
13,1/4/2020 21:23,597.240519,-230.177518,8018.670242,3014.685587,6.0,216.955988,-228.383125,NaN
14,1/4/2020 21:23,598.902643,-230.113140,8066.496529,3009.385194,6.0,216.600169,-228.324868,NaN
15,1/4/2020 21:23,595.617724,-229.839106,8004.947928,3005.211251,6.0,220.231937,-228.022992,NaN
16,1/4/2020 21:24,602.037550,-230.118253,7861.433626,2988.494153,6.0,234.675064,-228.334729,NaN
17,1/4/2020 21:24,599.079424,-229.673337,8136.617589,2993.202712,6.0,216.222601,-227.862092,NaN
18,1/4/2020 21:24,601.861362,-230.454105,7968.894785,3001.604306,6.0,227.236633,-228.651110,NaN
19,1/4/2020 21:24,600.350627,-230.392577,7980.952077,2997.277600,6.0,227.656871,-228.607837,NaN
20,1/4/2020 21:25,595.174459,-230.385215,8104.479775,2985.384814,6.0,211.825274,-228.582898,NaN
21,1/4/2020 21:25,594.183823,-229.856692,8158.518790,2994.514722,6.0,209.950035,-228.040168,NaN
22,1/4/2020 21:25,594.848380,-229.443856,7944.603986,3011.876748,6.0,219.542640,-227.637095,NaN
23,1/4/2020 21:25,596.878766,-230.179140,8149.775419,3004.365248,6.0,210.487693,-228.394809,NaN
24,1/4/2020 21:26,594.626818,-230.122249,7945.659049,3014.574605,6.0,222.930464,-228.334894,NaN
25,1/4/2020 21:26,601.175429,-230.013556,7890.802045,2992.929574,6.0,233.234553,-228.205613,NaN
26,1/4/2020 21:26,600.319959,-229.504242,8093.423637,3012.742536,6.0,216.459130,-227.687635,NaN
27,1/4/2020 21:26,601.022058,-229.988652,7920.305972,3009.159177,6.0,230.735156,-228.177206,NaN
28,1/4/2020 21:27,597.859398,-229.933137,8103.572883,2993.683985,6.0,214.499149,-228.150237,NaN
29,1/4/2020 21:27,604.592105,-229.901103,8004.786205,3007.167620,6.0,229.649188,-228.089953,NaN
...,...,...,...,...,...,...,...,...,...
296420,4/17/2020 10:25,603.683797,-229.529898,8146.369626,3005.039726,6.0,219.432346,-227.723023,NaN
296421,4/17/2020 10:25,603.338195,-229.801421,7865.222192,2996.985823,6.0,236.437821,-227.987629,NaN
296422,4/17/2020 10:25,596.376554,-230.485140,7953.683694,3002.147620,6.0,221.559484,-228.675612,NaN
296423,4/17/2020 10:25,597.094749,-229.557738,7979.412931,3012.602827,6.0,222.139043,-227.776695,NaN
296424,4/17/2020 10:26,601.615218,-229.889949,7990.162351,2996.824190,6.0,227.996735,-228.097940,NaN
296425,4/17/2020 10:26,601.413982,-230.359813,7959.189696,3014.886996,6.0,228.124747,-228.580269,NaN
296426,4/17/2020 10:26,594.388420,-230.413627,7849.238546,2986.899212,6.0,226.691830,-228.632718,NaN
296427,4/17/2020 10:26,600.639907,-229.550869,7915.106314,3003.155269,6.0,229.472044,-227.740460,NaN
296428,4/17/2020 10:27,600.565028,-229.934543,8041.855579,3008.632224,6.0,222.580241,-228.149878,NaN
296429,4/17/2020 10:27,601.786191,-230.060314,7844.024104,2992.816616,6.0,237.959096,-228.262368,NaN
296430,4/17/2020 10:27,603.308857,-230.231906,7998.606450,2998.431180,6.0,229.394172,-228.446662,NaN
296431,4/17/2020 10:27,601.211184,-229.702701,8016.527811,3005.156706,6.0,222.184837,-227.919752,NaN
296432,4/17/2020 10:28,595.914979,-230.564724,7918.775566,3009.478837,6.0,223.799126,-228.775736,NaN
296433,4/17/2020 10:28,603.197592,-229.561077,8085.700040,2999.944273,6.0,220.815169,-227.744058,NaN
296434,4/17/2020 10:28,595.713277,-229.728296,7867.676545,2986.438510,6.0,231.173806,-227.946408,NaN
296435,4/17/2020 10:28,602.662057,-229.736901,8022.519717,3011.107780,6.0,225.225993,-227.952063,NaN
296436,4/17/2020 10:29,600.056953,-230.268763,8046.267276,2993.732231,6.0,224.060583,-228.468155,NaN
296437,4/17/2020 10:29,601.179962,-229.818048,7969.428509,2997.766708,6.0,228.492945,-228.017536,NaN
296438,4/17/2020 10:29,605.348416,-229.533638,7866.677490,2986.329442,6.0,240.737762,-227.746067,NaN
296439,4/17/2020 10:29,599.170993,-230.002659,8127.726865,3012.491215,6.0,216.301584,-228.221312,NaN
296440,4/17/2020 10:30,597.084555,-229.669928,7865.169791,3008.508909,6.0,226.979021,-227.850999,NaN
296441,4/17/2020 10:30,604.364515,-230.492112,8007.403138,3005.001822,6.0,227.261131,-228.705144,NaN
296442,4/17/2020 10:30,596.399658,-229.626672,8011.935870,3007.311305,6.0,219.191069,-227.816308,NaN
296443,4/17/2020 10:30,602.417900,-230.239888,7867.496868,3003.601850,6.0,233.695667,-228.443238,NaN
296444,4/17/2020 10:31,602.159512,-230.169859,8036.656673,3012.042421,6.0,223.720528,-228.350499,NaN
296445,4/17/2020 10:31,596.611125,-230.191381,7959.768879,2997.812618,6.0,221.753096,-228.401583,NaN
296446,4/17/2020 10:31,597.319541,-230.084466,7947.662310,3004.436412,6.0,225.208842,-228.284966,NaN
296447,4/17/2020 10:31,604.480493,-230.162283,7944.993098,2999.621114,6.0,231.336761,-228.339348,NaN
296448,4/17/2020 10:32,605.071293,-229.547767,8107.651750,3008.993634,6.0,220.675692,-227.760228,NaN
296449,4/17/2020 10:32,595.669526,-230.493843,8151.621431,3006.425541,6.0,207.931428,-228.692008,NaN

In [35]:
independent_val=dataset.iloc[:,[1,2,3,4,5,7]].values
dependent_val=dataset.iloc[:,6]

(296450,)

In [20]:
from sklearn.model_selection import train_test_split

In [22]:
independent_val_train,independent_val_test,dependent_val_train,dependent_val_test=train_test_split(independent_val,dependent_val,test_size=0.2,random_state=0)

In [48]:
from sklearn.linear_model import LinearRegression
model=LinearRegression()
model.fit(independent_val_train,dependent_val_train)
pickle.dump(model, open(r'C:\Users\Lenovo\Desktop\Mechademy\assignment_2.pickle', 'wb'))
loaded_model=pickle.load(open(r'C:\Users\Lenovo\Desktop\Mechademy\assignment_2.pickle', 'rb'))

In [49]:
loaded_model.predict(independent_val_test)

array([222.72814225,  83.96880061, 176.73937796, ..., 155.73502175,
       155.11487864, 184.38247478])

In [37]:
dependent_val_test

274942    223.476846
49603      80.235425
82487     177.581833
61469      86.535143
266616    215.612215
195029    153.183302
293957    219.789844
120245    237.248570
125900    227.508133
225940    131.544095
39446     121.269557
215677    132.831347
281581    227.698178
23581     303.962946
21738     300.067930
53985     101.354226
58481     101.825071
156600    205.875116
8320      154.186767
150414    195.701663
73227     151.757001
75248     172.635288
185170    158.154408
232998    143.509228
35653     142.168187
79306     179.478100
220790    141.469887
139475    236.415265
177838    150.210326
231868    144.745186
             ...
20436     318.486713
272808    216.239266
68676     129.900930
282153    235.452387
104154    308.091169
42103     129.222926
103345    305.436851
18716     264.293470
40214     145.068445
132316    240.587698
227903    136.889162
131121    232.415390
196423    119.839242
57159      87.676724
235348    157.482049
261599    207.210409
64255     102.623414
63676      74.774384
69835     170.531812
221050    149.412542
102545    288.336634
11803     151.033048
222512    132.032301
197135    141.273824
165828    195.048313
227584    145.726869
5358      168.146779
31238     156.945701
189252    155.751617
93609     186.442307
Name: Discharge Pressure (psig), Length: 59290, dtype: float64